default: &default
  adapter: postgresql
  pool:    5
  timeout: 5000

local_credentials: &local_credentials
  username: aschen
  password: aschen

development:
  <<: *default
  <<: *local_credentials
  database: convert_my_coin_development

test: &test
  <<: *default
  <<: *local_credentials
  database: convert_my_coin_test
